name: Github Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: treeform/setup-nim-action@v6
      - run: nimby install chroma -g
      - run: nimby install flatty -g
      - run: nimby install opengl -g
      - run: nimby install pixie -g
      - run: nimby install vmath -g
      - run: nimby install webby -g
      - run: nimby install windy -g
      - run: nim check src/gltf.nim
      - run: nim r tests/tests.nim
